// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export interface ClusterKindConfig {
    apiVersion: pulumi.Input<string>;
    containerdConfigPatches?: pulumi.Input<pulumi.Input<string>[]>;
    featureGates?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    kind: pulumi.Input<string>;
    networking?: pulumi.Input<inputs.ClusterKindConfigNetworking>;
    nodes?: pulumi.Input<pulumi.Input<inputs.ClusterKindConfigNode>[]>;
    runtimeConfig?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
}

export interface ClusterKindConfigNetworking {
    apiServerAddress?: pulumi.Input<string>;
    apiServerPort?: pulumi.Input<number>;
    disableDefaultCni?: pulumi.Input<boolean>;
    dnsSearches?: pulumi.Input<pulumi.Input<string>[]>;
    ipFamily?: pulumi.Input<string>;
    kubeProxyMode?: pulumi.Input<string>;
    podSubnet?: pulumi.Input<string>;
    serviceSubnet?: pulumi.Input<string>;
}

export interface ClusterKindConfigNode {
    extraMounts?: pulumi.Input<pulumi.Input<inputs.ClusterKindConfigNodeExtraMount>[]>;
    extraPortMappings?: pulumi.Input<pulumi.Input<inputs.ClusterKindConfigNodeExtraPortMapping>[]>;
    image?: pulumi.Input<string>;
    kubeadmConfigPatches?: pulumi.Input<pulumi.Input<string>[]>;
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    role?: pulumi.Input<string>;
}

export interface ClusterKindConfigNodeExtraMount {
    containerPath?: pulumi.Input<string>;
    hostPath?: pulumi.Input<string>;
    propagation?: pulumi.Input<string>;
    readOnly?: pulumi.Input<boolean>;
    selinuxRelabel?: pulumi.Input<boolean>;
}

export interface ClusterKindConfigNodeExtraPortMapping {
    containerPort?: pulumi.Input<number>;
    hostPort?: pulumi.Input<number>;
    listenAddress?: pulumi.Input<string>;
    protocol?: pulumi.Input<string>;
}
